name: CI Docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
            access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Docs / Install Dependencies
        run: cd docs && yarn
      - name: Docs / Build Documentation
        run: cd docs && yarn build
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.directories.outputs.LIST }}
          fail_on_error: true
          vale_flags: "--minAlertLevel=error --config=docs/.vale.ini"
          reporter: github-pr-check
          token: ${{ github.token }}
          filter_mode: nofilter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}